obsidianforensics/unfurl

- parsers/parse_base64.py
- parsers/parse_discord.py
- parsers/parse_domain.py
- parsers/parse_url.py
- unfurl.py
> Add scheme and port extraction

- .gitignore
- parsers/parse_ksuid.py
- tests/integration/test_api.py
- Add a gitignore file.
- Add and integration test, (basic one) just to check if status_code is OK (200) when home url and api url are called. It is following #33 discussion.
- Add of ksuid parser
> Integration test + gitignore + ksuid parser 

- tests/unit/test_base64.py
- tests/unit/test_twitter.py
> Base64 tests

- .gitignore
- README.md
- templates/graph.html
- unfurl.ini
- unfurl_app.py
Fixes #24: Adds a config file (```unfurl.ini```) where host, port, and debug can be specified.
> Add config file

- Dockerfile
- README.md
- docker-compose.yaml
- templates/graph.html
> Add Docker Support

- __init__.py
- parsers/parse_compressed.py
- parsers/parse_url.py
- static/styles.css
- templates/graph.html
- unfurl.py
Starts to address #13. Adds b64+zip decoding.
> Compression

- parsers/parse_bitly.py
- parsers/parse_url.py
- requirements.txt
- tests/unit/test_bing.py
- tests/unit/test_bitly.py
> The parser for Bitly URL shortner 

- parsers/parse_bitly.py
- parsers/parse_google.py
- parsers/parse_shortlink.py
- unfurl.py
Fixes #42 
Adds support for more shortlinks
> More shortlinks

- parsers/parse_shortlink.py
Adds even more short links #42
> Add four more short link domains I've run across.

- .gitignore
- parsers/blackboxprotobuf/__init__.py
- parsers/blackboxprotobuf/lib/interface.py
- parsers/blackboxprotobuf/lib/types/__init__.py
- parsers/blackboxprotobuf/lib/types/fixed.py
- parsers/blackboxprotobuf/lib/types/length_delim.py
- parsers/blackboxprotobuf/lib/types/type_maps.py
- parsers/blackboxprotobuf/lib/types/varint.py
- parsers/parse_protobuf.py
- parsers/parse_uuid.py
Adds parsing of protobufs, without needing the proto definition. Leverages blackboxprotobuf lib.
> Unknown Protobufs

- parsers/parse_magnet.py
- parsers/parse_url.py
- requirements.txt
> Add parse_magnet.py, for parsing BitTorrent Magnet Link files

- parsers/parse_google.py
Fixes #56 
Updated ei parameter description to reflect it likely applies to the whole session, not the individual search.
> Update ei parameter description

- README.md
- unfurl_cli.py
> Add support for reading file as input and writing CSV file output.

- requirements.txt
- unfurl/parsers/parse_google.py
- unfurl/tests/unit/test_google.py
Add another Google param, per #2
> Add parsing of RLZ values in Google URLs (and a test)

- unfurl/parsers/parse_google.py
> Add support for Google Search Type

- unfurl/parsers/parse_base64.py
- unfurl/parsers/parse_bing.py
- unfurl/parsers/parse_compressed.py
- unfurl/parsers/parse_discord.py
- unfurl/parsers/parse_google.py
- unfurl/parsers/parse_mailto.py
- unfurl/parsers/parse_protobuf.py
- unfurl/parsers/parse_timestamp.py
Updates ei param parsing, per #2
> Update ei timestamp

- Dockerfile
Reference #77, this is a change to the Dockerfile to build from the local files.
> Build Docker image from local source

- unfurl/parsers/__init__.py
- unfurl/parsers/parse_mac_addr.py
- unfurl/parsers/parse_sonyflake.py
- unfurl/tests/unit/test_sonyflake.py
> Sonyflake parsing

- unfurl/parsers/parse_sonyflake.py
- unfurl/parsers/parse_timestamp.py
> Add epoch hex and Windows FileTime hex formats.

- unfurl/parsers/parse_bing.py
- unfurl/parsers/parse_uuid.py
- unfurl/tests/unit/test_bing.py
> Add translating the names of more Bing QSPs

- unfurl/parsers/parse_youtube.py
- unfurl/tests/unit/test_youtube.py
> Add YouTube tests and add parsing for t=xs values

- unfurl/parsers/parse_base64.py
- unfurl/parsers/parse_json.py
- unfurl/tests/unit/test_base64.py
> Fix JSON hover text, rework b64 output data_type, and update tests.

- unfurl/parsers/__init__.py
- unfurl/parsers/parse_dropbox.py
> Add basic parsing of Dropbox preview URLs.

- unfurl/parsers/parse_protobuf.py
- unfurl/parsers/parse_url.py
> More generic qsps

- unfurl/static/styles.css
- unfurl/templates/graph.html
> New example page

- unfurl/parsers/parse_google.py
> Add browser window width & height parameters

- setup.py
- unfurl/parsers/parse_url.py
- unfurl/tests/unit/test_url.py
> Add parsing of file name & extension if part of URL path

- unfurl/parsers/parse_uuid.py
> Adds Laravel Ordered UUID parsing

- .github/workflows/publish-to-test-pypi.yml
- setup.py
- unfurl/__init__.py
- unfurl/core.py
- unfurl/parsers/parse_discord.py
- unfurl/parsers/parse_json.py
- unfurl/parsers/parse_ksuid.py
- unfurl/parsers/parse_sonyflake.py
- unfurl/parsers/parse_tiktok.py
- unfurl/parsers/parse_twitter.py
> Add logging

- unfurl/parsers/parse_shortlink.py
Adds more as noted in #42 
Examples:
- https://t.ly/NYFE
- https://urlwee.com/unfurl/
> Added two more link shortener sites: t.ly and urlwee.com

- unfurl/parsers/parse_uuid.py
- unfurl/tests/unit/test_hashes.py
> Limit UUID regex to match UUIDs v1-5

- unfurl/core.py
- unfurl/parsers/parse_google.py
- unfurl/tests/unit/test_google.py
- unfurl/utils.py
Add parsing for Google Search "aqs" parameter (Assisted Query Stats)
> Add parsing for Google Search "aqs" parameter 

- requirements.txt
- unfurl/core.py
- unfurl/parsers/parse_domain.py
- unfurl/tests/unit/test_bing.py
- unfurl/tests/unit/test_discord.py
- unfurl/tests/unit/test_google.py
- unfurl/tests/unit/test_hashes.py
- unfurl/tests/unit/test_metasploit.py
- unfurl/tests/unit/test_shortlink.py
- unfurl/tests/unit/test_twitter.py
- unfurl/tests/unit/test_url.py
- unfurl/tests/unit/test_youtube.py
> Use MISP "warning lists" to enrich domain names

- unfurl/core.py
- unfurl/parsers/parse_google.py
- unfurl/parsers/parse_timestamp.py
- unfurl/utils.py
Fixes #81 and adds a few cases utilizing multiple parents.
> Adds supports for nodes to have multiple parents

- unfurl/parsers/parse_shortlink.py
> Add URL redirect lookup for another type of Linkedin link shortener.

- .github/workflows/unit-tests.yml
- unfurl/__init__.py
> Update version for release

- setup.py
> Also update setup.py with new dependency versions

- setup.py
- unfurl/__init__.py
> Up version number for 2022.11 release

- .github/workflows/publish-to-pypi.yml
- setup.py
> Packaging debug

- requirements.txt
- unfurl/parsers/__init__.py
- unfurl/parsers/parse_base64.py
- unfurl/parsers/parse_dns.py
- unfurl/tests/unit/test_dns.py
> Add parser (and test) for DNS DoH URLs

- requirements.txt
- unfurl/core.py
- unfurl/parsers/parse_shortlink.py
> Adjust for changes in `pymispwarninglists`

- unfurl/__init__.py
- unfurl/app.py
- unfurl/core.py
> Move the `run` function into `core.py`

- unfurl/parsers/parse_timestamp.py
- unfurl/tests/unit/test_timestamps.py
> Fix bug with hex-based timestamp conversions; add covering tests.

- pyproject.toml
- unfurl/cli.py
- unfurl/core.py
> Optimizations for doing multiple lookups with an Unfurl instance

- unfurl/core.py
- unfurl/parsers/parse_mac_addr.py
> Add descriptor for potentially randomized MAC addresses

- unfurl/parsers/parse_google.py
> Google updates - add parsing of `udm` parameter and modify "two-parent" nodes

- unfurl/core.py
- unfurl/parsers/__init__.py
- unfurl/parsers/parse_initial_node.py
> Add some clean-up actions to help the initial user input be parseable

- unfurl/parsers/parse_timestamp.py
> Increase maximum "reasonable" timestamp to 2030

- unfurl/parsers/parse_bluesky.py
> Fix import

- unfurl/parsers/parse_timestamp.py
- unfurl/tests/unit/test_linkedin.py
- unfurl/tests/unit/test_twitter.py
> Add `datetime.UTC` as tzinfo for timestamp nodes
